@baseUrl = http://localhost:3000

### Get all users
GET {{baseUrl}}/users

### Get a user by ID
GET {{baseUrl}}/users/1

### Create a user (valid)
### @name CreateUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "trung",
  "full_name": "Trung Nguyen Van",
  "email": "trung@otmc.com.vn",
  "content": "{\"key\": \"value\"}"
}


### Delete a user (valid)
DELETE {{baseUrl}}/users/2

### Create a user (missing username -> validation error)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "trung@otmc.dev"
}

### Create a user (invalid email -> validation error)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "trung",
  "email": "not-an-email"
}