// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type User struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	FullName  sql.NullString `json:"full_name"`
	Email     string         `json:"email"`
	Content   sql.NullString `json:"content"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
